name: kanbatask
description: "Manager projects, teams and tasks with KanbaTask"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  firebase_remote_config: ^5.4.7

  # Other dependencies
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  go_router: ^16.0.0

  equatable: ^2.0.7
  google_fonts: ^6.2.1
  gap: ^3.0.1
  cached_network_image: ^3.3.0

  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  table_calendar: ^3.1.3
  very_good_infinite_list: ^0.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/google_fonts/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
