// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0iGP3aw79Gt3LZqxoj64qMKte5QNcAqo',
    appId: '1:786370361776:web:feceebf23d6f011812fe75',
    messagingSenderId: '786370361776',
    projectId: 'kanbatask-d095b',
    authDomain: 'kanbatask-d095b.firebaseapp.com',
    storageBucket: 'kanbatask-d095b.firebasestorage.app',
    measurementId: 'G-S5Q4S2VKYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGkZhTPuNhrdLp2X71yx6yl8eGXdjgl8',
    appId: '1:786370361776:android:f6d3fa61293add1212fe75',
    messagingSenderId: '786370361776',
    projectId: 'kanbatask-d095b',
    storageBucket: 'kanbatask-d095b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwXZNbZd-UMtOlo2PpBRPEzTRTY24xVUs',
    appId: '1:786370361776:ios:5d8995992057c9c112fe75',
    messagingSenderId: '786370361776',
    projectId: 'kanbatask-d095b',
    storageBucket: 'kanbatask-d095b.firebasestorage.app',
    iosBundleId: 'com.catundastudio.kanbatask',
  );
}
